[package]
name = "aureline-cli"
description = "Aureline command-line interface."
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "aureline"
path = "src/main.rs"

[dependencies]
aureline-lang = { path = "../lang" }

[lints]
workspace = true
