[package]
name = "aureline-parser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Aureline parser entrypoints."
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
aureline-ast = { path = "../ast" }
chumsky = "0.13.0"

[lints]
workspace = true
